### ISSUE TITLE
Big video stream

### ISSUE THREAD

**Issue by hasanitman** [JRoy/InstagramLive-PHP#1]
Hello
i use it and it worked. but the video streaming is very big like someone zoomed in camera
can u help me to fix it ?

**Comment by JRoy** [comment]
Instagram only *natively* supports vertical video. You'd need to flip it on the client side.

**Comment by hasanitman** [comment]
do u check it ?
it's very big, not just horizental

**Comment by JRoy** [comment]
@hasanitman, Instagram only takes the center portion of the horizontal video. You'll need to adapt your content that you're sending out to the center portion.

**Comment by hasanitman** [comment]
ty for reply
but why same scene in mobile good, just when i use cemera it's much bigger than mobile
i see in live.php resolution, but it's didn't work
do u have idea why ?

**Comment by hasanitman** [comment]
plz can u take a time and see if we can add some resolution
thanks for u

**Comment by JRoy** [comment]
@hasanitman, The script provides the credentials to use Instagram with third-party streaming platforms. For this to be resolved, you would need to change the output setting to 720x1280 on **your end**.

This script never sees the content being sent to Instagram, so I have no way of modifying it/changing the resolution.

**Comment by hasanitman** [comment]
do u mean if i stream with 720*1280, the problem will solved?

**Comment by JRoy** [comment]
@hasanitman: That *should* fix it

**Comment by hasanitman** [comment]
yes, it's work now 👍 
but i think i can't use my canon 5D camera and Instagram script in same time
because the resolution is very different
do u have idea for fixing this problem?
and i thanks u again for very good script :)

**Comment by JRoy** [comment]
I don't know how to fix that issue, sorry.

**Comment by hasanitman** [comment]
Thanks a lot :)
👍

**Comment by marcosgonzaleztv** [comment]
Thanks, this helped me out a ton too!
