### ISSUE TITLE
Only override necessary settings for OBS integration

### ISSUE THREAD

**Issue by sneaky4oe** [JRoy/InstagramLive-PHP#101]
When you click "yes, i want to use obs", it crashes already running instance, and can't launch it itself. It, however, manages to hook up to OBS and update it's settings related to key, but for some reason also breaks encoder preset. I use x264 superfast, but it uses simplified output, which lags my laptop :-(

**Comment by JRoy** [comment]
I can make it so obs integration will not alter any additional settings than it needs to.

Cheers

**Comment by sneaky4oe** [comment]
It also looks like Instagram streaming resolution is 480px. (judging by the details preserved in the image) compared to a scaled original image. 
And what about script crashing already working obs on start and not being able to start it by itself?

**Comment by JRoy** [comment]
That makes no sense, do you get errors?

**Comment by sneaky4oe** [comment]
![image](https://user-images.githubusercontent.com/3416242/52789755-d6872a00-3075-11e9-8f91-f83409bd3b6b.png)

**Comment by sneaky4oe** [comment]
OBS is installed to default location.
![image](https://user-images.githubusercontent.com/3416242/52789803-fa4a7000-3075-11e9-911a-0ecaf20ba4a1.png)

To be sure it can be accessed I even added it to PATH, but it didn't help. 

As for closing existing OBS, looks absolutely the same way but it knows that it kills obs
![image](https://user-images.githubusercontent.com/3416242/52789898-354ca380-3076-11e9-8721-e85ae4f40c88.png)

**Comment by JRoy** [comment]
That's extremely odd, maybe it will magically be fixed in the next version
