### ISSUE TITLE
New update Not working

### ISSUE THREAD

**Issue by sharmilasudhakar** [JRoy/InstagramLive-PHP#102]
Hi,
OS: Linux 
I followed the instruction as per the document but i get an error saying, "sh: 1: composer.phar: not found" but it is present in the folder and I couldn't see the vendor folder.

>php update.php
Fetching Latest Stable Release Data
Fetched Version: 1.3
Comparing Files...
File Queued: goLive.php
File Queued: commandLine.php
File Queued: utils.php
File Queued: obs.php
File Queued: composer.json
update.php: 22ac7984295af6d85f016a28d1afc5a1 - 22ac7984295af6d85f016a28d1afc5a1
Checking for config updates...
No config detected, downloading...
Downloaded config!
Updating 5 files...
Files Updated!
Detected composer update, re-installing
**sh: 1: composer.phar: not found**
InstagramLive-PHP is now up-to-date!

>php goLive.php
Loading InstagramLive-PHP v1.3...
The following file, `somepath/instagramlive/vendor/autoload.php` is required and not found by the script for the following reason: Instagram API Files
Please make sure you follow the setup guide correctly.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.3
InstagramLive-PHP Flavor: stable
Operating System: Linux
PHP Version: 7.2.10-0ubuntu0.18.04.1
PHP Runtime: cli
PHP Binary: /usr/bin/php7.2
Bypassing OS-Check: false
Composer Lock: false
Vendor Folder: false
============END DUMP============

Is this the issue with the composer (or) with the issue in the new update you have raised in the [link](https://github.com/JRoy/InstagramLive-PHP/issues/99) 
I even tried with the older releases but none worked for me? Can you help me in this issue ?

**Comment by JRoy** [comment]
This is a composer issue, you must install composer.

**Comment by sharmilasudhakar** [comment]
I have installed composer yet it din't work. The composer.phar file is present inside the folder.

**Comment by JRoy** [comment]
@sharmilasudhakar in that case run `php composer.phar install`
