### ISSUE TITLE
Solution for non-English languages pin-comment on startup 

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#104]
Dear Roy 
For solve this problem (I think) can use chcp 65001 in CMD.
Although the problem of non-English languages in CMD is not your script problem but I think it is helpful for some people to know this.
thanks

**Comment by JRoy** [comment]
Yeah the command prompt is absolute hell for non English letters, I'll make a warning and a command line argument to change the chcp mode for windows users
