### ISSUE TITLE
Use ffmpeg and local RTMP server

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#105]
Dear Roy
Although stream-key in OBS is automatically copied and run with this script, but it is not in VMIX. So the best way is install a rtmp server like nginx (https://obsproject.com/forum/resources/how-to-set-up-your-own-private-rtmp-server-using-nginx.50/) and use vmix for stream to local rtmp server and then use ffmpeg for stream to instagram.

(To use ffmpeg after installing it) It's enough to be replaced 

`Utils::log("Logged In! Creating Livestream...");
		$ffmpegPath = null;
        $ffmpeg = \InstagramAPI\Media\Video\FFmpeg::factory($ffmpegPath);
        $stream = $ig->live->create();
        $broadcastId = $stream->getBroadcastId();
        $ig->live->start($broadcastId);
        // Switch from RTMPS to RTMP upload URL, since RTMPS doesn't work well.
        $streamUploadUrl = preg_replace(
            '#^rtmps://([^/]+?):443/#ui',
            'rtmp://\1:80/',
            $stream->getUploadUrl()
        );
        /////// MEDIA ////////
        $videoFilename = 'rtmp://"yourlocalip"/live';
        //////////////////////
        $broadcastProcess = $ffmpeg->runAsync(sprintf(
            '-rtbufsize 256M -re -i %s  -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s',
            \Winbox\Args::escape($videoFilename),
            \Winbox\Args::escape($streamUploadUrl)
        ));`

instead of

` Utils::log("Logged In! Creating Livestream...");
        $stream = $ig->live->create();
        $broadcastId = $stream->getBroadcastId();
        // Switch from RTMPS to RTMP upload URL, since RTMPS doesn't work well.
        $streamUploadUrl = (!useRmtps === true ? preg_replace(
            '#^rtmps://([^/]+?):443/#ui',
            'rtmp://\1:80/',
            $stream->getUploadUrl()
        ) : $stream->getUploadUrl());
`

**Comment by sharmilasudhakar** [comment]
Hi,
I tried to stream a mp4 video to the instagram rtmp url using ffmpeg but it didn't work. I  It showed me in the terminal as streaming but i couldn't see the output video in the instagram.
Command used,
ffmpeg -re -i video.mp4 -b:a 128k -acodec aac -ar 48000 -ac 1 -b:v 2100k -vcodec libx264 -r 30 -filter:v scale=w=720:h=1280 -f flv -pix_fmt yuv420p -preset ultrafast -bufsize 8000k -g 250 -keyint_min 24 -profile High -level 3.0 "instagramrtmpurl"

Can you please guide me where i am wrong?

**Comment by JRoy** [comment]
This is outside the scope of the script, I don't want to have to deal with video processing. Sorry.
