### ISSUE TITLE
Not able to launch OBS (1.4 version)

### ISSUE THREAD

**Issue by sneaky4oe** [JRoy/InstagramLive-PHP#108]
![image](https://user-images.githubusercontent.com/3416242/53031022-0884fb80-347d-11e9-9078-10da6a3e2f3f.png)

**Comment by sneaky4oe** [comment]
It is still able to kill OBS, but can't launch it back. 
![image](https://user-images.githubusercontent.com/3416242/53031192-69143880-347d-11e9-877a-ff5082350572.png)

**Comment by JRoy** [comment]
Hi @sneaky4oe, can you provide a screenshot of where your obs64.exe is located. (Make sure to include its path in the screenshot).

**Comment by sneaky4oe** [comment]
![image](https://user-images.githubusercontent.com/3416242/53031621-4171a000-347e-11e9-8b3f-d260746b53ff.png)

**Comment by JRoy** [comment]
This is odd, have you tried reinstalling obs

**Comment by sneaky4oe** [comment]
Just did:
![image](https://user-images.githubusercontent.com/3416242/53089669-4128e180-351e-11e9-820f-65c61182caa8.png)

Still getting the same error:
![image](https://user-images.githubusercontent.com/3416242/53089700-57cf3880-351e-11e9-9e1a-2e3b4e63e94d.png)

**Comment by JRoy** [comment]
I have no idea then, this is probably a Windows issue as the rest of the users and I are unable to reproduce this. Sorry

**Comment by sneaky4oe** [comment]
Maybe add some debugging lines like "trying to launch %path%"? I bet something is just off with that even despite obs is in default location.
