### ISSUE TITLE
Add web-application to see comments 

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#117]
Dear Roy

Can you add web application similar to loola.tv to see comments?(http://s9.picofile.com/file/8353201268/1111111111111111111111.png)

thanks

**Comment by JRoy** [comment]
This is accomplished with the windows duel terminal solution, I don't get what this would add?

**Comment by ahmadd110** [comment]
Because it does not display correctly non-English comments (RTL)
