### ISSUE TITLE
Script exited while live

### ISSUE THREAD

**Issue by jkopelman** [JRoy/InstagramLive-PHP#118]
Was streaming for a while, the main script error'd out. The livestream continued but was no longer able to end the stream or gather analytics or post to stories. 

Error While Creating Livestream: No response from server. Either a connection or configuration error.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.5
InstagramLive-PHP Flavor: beta
Operating System: WINNT
PHP Version: 7.3.2
PHP Runtime: cli
PHP Binary: C:\xampp\php\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Exception: No response from server. Either a connection or configuration error.
============END DUMP============

**Comment by JRoy** [comment]
Odd? Maybe try again in 4 days as that's how long it takes Instagram to cool off. Also while the script supports infinite stream, I don't recommend doing more than 2hours of streaming a day.
