### ISSUE TITLE
help for MacBokk

### ISSUE THREAD

**Issue by rafaelcarlota** [JRoy/InstagramLive-PHP#12]
Hello, JRoy. 

Friend I'm having trouble setting up the application on macbook.

- I installed XAMP 7.2.1 on my macbook.

- I installed Composer using these commands:

> php -r "copy ('https://getcomposer.org/installer', 'composer-setup.php');
> 
> php -r "if (hash_file ('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abcfd3d3c4b4f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') {echo 'Installer verified';} else {echo 'Installer corrupt'; unlink ('composer-setup. php ');} echo PHP_EOL; "
> 
> php composer-setup.php
> 
> php -r "unlink ('composer-setup.php');

- Download your files. I changed login and password of the config.php file

When will I execute this command

composer require mgp25 / instagram-php react / child-process

He does not accept it.

I'm following step by step everything you've done in the video, I've refaced the process and still can not.

Can you help me.

**Comment by JRoy** [comment]
Hello!

Composer's install guide is not that well written as it does not show you how to move composer into your path. I suggest [this tutorial](https://www.abeautifulsite.net/installing-composer-on-os-x) for installing composer on mac

**Comment by rafaelcarlota** [comment]
JRoy, I got it sorted out. Thank you for your help.

You can tell me how long I can stay alive in instagram and if the video with 1 or 2 hours of live is in the stories.

I'll make a donation for you, your sensational work.

**Comment by JRoy** [comment]
@rafaelcarlota for unverified users, it's 1 hour of streaming. Otherwise it's unlimited. I appreciate your interest in making a donation :)
