### ISSUE TITLE
Add obs path search strings to the config

### ISSUE THREAD

**Issue by ansius** [JRoy/InstagramLive-PHP#122]
Hi!

Thanks for awesome script!

had a problem that obs-studio did not launch automatically, windows was screaming that it can't find it, yet script configured it properly. also found the reason and workaround.

in obs.php it is spawnOBS procedure and obs-studio is run with following commands:
`pclose(popen("cd \"$this->obs_path" . "bin/64bit\" && start /B obs64.exe" . ($this->autoStream ? " --startstreaming" : "") . " --profile $this->profile_name", "r"));`

yet it only works correctly if the script it self is located on the same drive as obs-studio, either you have to add the "c:" command before (popen("C: && cd \"), or the script has to be located on the C: drive. it is more related to the way command prompt in windows works than the php script.

I'm not the most versed in the github so someone please make the change to code (i think script should be aware the drive it is on for windows machines), or if someone else stumbles on this problem, here is the workaround - have the script on the same drive (as I read code, assuming C: is rather hard coded, it should maybe be an config.ini option for absolute path for custom installations).

Thanks and good luck evryone!

**Comment by JRoy** [comment]
@ansius I can add a config.php option for the obs paths

**Comment by ansius** [comment]
Thanks, that would be grate!

It is nice that the script does self probe for location (to get the stream settings), and maybe it could if while first run, write it in the config, if it is not set there. And leave the manual setting, if it is set an display a warning that obs was not found, please edit the config manually? That would make the best case scenario transparent for regular user, but enough info for a problematic setup or manual system. 

I just took me quite a while to understand why the command issued "cd" did not  accomplish trough script but worked if i copied it (the generated output i used utill::log to see what is wrong) to command prompt it worked.

just adding a absolute path will not help the "cd" command as it does not change the drive with absolute path, you have to select the drive with "c:" command and then you can "cd" and run the program. 

of course you can just direct path run the program, but it might generate some security problems on a more tightly installed windows setup, and while searching for a cause I did modify the spawnOBS with a hard coded command, yes it launched, but obs throw an error that could not find it's config files, as it would been moved out of the folder.

what ever way you decide to change, i will test it, i have several machines that all use different windows versions and setup.

thank you again!

**Comment by JRoy** [comment]
> It is nice that the script does self-probe for location (to get the stream settings), and maybe it could if while first run, write it in the config if it is not set there. And leave the manual setting, if it is set an display a warning that obs was not found, please edit the config manually? That would make the best case scenario transparent for the regular user, but enough info for a problematic setup or manual system.

The way the settings work now is before the launch of OBS, it searches for the settings file(s) and backs them up. It is then altered to Instagram's settings and OBS is launched. Once the stream ends, we revert to the old settings state so that users can keep their existing obs settings while using this script.

---

> just adding an absolute path will not help the "cd" command as it does not change the drive with the absolute path, you have to select the drive with "c:" command and then you can "cd" and run the program.

Window's `cd` command **can** change drives. In 1.5, when this feature will be added, all you have to do is fill out the OBS_CUSTOM_PATH definition to something like `D:/path/to/obs/`
https://github.com/JRoy/InstagramLive-PHP/blob/c459879872a7e2862cb99471a1b579a76ac39b0b/config.php#L13

---

> of course, you can just direct path run the program, but it might generate some security problems on a more tightly installed windows setup, and while searching for a cause I did modify the spawnOBS with a hard-coded command, yes it launched, but obs throw an error that could not find it's config files, as it would be moved out of the folder.

I'm not sure to which security issues you are referring to, as I can just blame the user when something goes wrong 😄. Anyway, the new system coming in 1.5 will allow for a separate path and executable names so that may fix your issues.
https://github.com/JRoy/InstagramLive-PHP/blob/c459879872a7e2862cb99471a1b579a76ac39b0b/config.php#L14

**Comment by JRoy** [comment]
Feature added in 1.5

Please run your `update.php` file to grab this new update!
