### ISSUE TITLE
Open automatically commandLine.php

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#123]
Dear Roy
How can I delete Enter so that commandLine.php open automatically? (line 204 "please press enter!")

thanks

**Comment by JRoy** [comment]
@ahmadd110 the warning is there to give you time to start streaming, I suppose I can make a command line argument for it tho

**Comment by ahmadd110** [comment]
Thanks a lot

**Comment by JRoy** [comment]
Added in 1.5.q
