### ISSUE TITLE
Can't go live

### ISSUE THREAD

**Issue by foreverme234** [JRoy/InstagramLive-PHP#127]
I can't seem to log into my Instagram for a live video, i'm getting the below message:
InstagramLive-PHP Version: 1.5.1
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#1598f2e3cdf05bea6cef89c9a6ec64c6167f1794
Operating System: WINNT
PHP Version: 7.2.16
PHP Runtime: cli
PHP Binary: C:\Users\Dave\Desktop\php-7.2.16-nts-Win32-VC15-x64\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true

I have done a fresh install and made sure it's up to date..

Please can you advise

**Comment by JRoy** [comment]
Your IP address may blocked by Instagram
