### ISSUE TITLE
Cant use Live instragram

### ISSUE THREAD

**Issue by foreverme234** [JRoy/InstagramLive-PHP#128]
I'm having issues using the script, I've installed it twice, updated it and tried in two different locations. I have tried multiple accounts. I have also verified the accounts multiple times 

I am getting the below:

Logging into Instagram! Please wait as this can take up-to two minutes...
Suspicious Login: Would you like to verify your account via text or email? Type "yes" or just press enter to ignore.
Suspicious Login: Please only attempt this once or twice if your attempts are unsuccessful. If this keeps happening, this script is not for you :(.
>
Suspicious Login: Account Challenge Failed :(.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.5.1
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#1598f2e3cdf05bea6cef89c9a6ec64c6167f1794
Operating System: WINNT
PHP Version: 7.3.3
PHP Runtime: cli
PHP Binary: C:\Users\Dave\Desktop\php-7.3.3-Win32-VC15-x64\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true

any advice?

**Comment by JRoy** [comment]
Have you logging into instagram.com from that computer and are you using the same wifi as the app on the phone?

**Comment by foreverme234** [comment]
Haven't tried logging into my phone, as it was a test instagram! I will give it a go.

Thank you
