### ISSUE TITLE
 Is it possible to turn on auto live after the end of the hour limit instagram?

### ISSUE THREAD

**Issue by be2clack** [JRoy/InstagramLive-PHP#129]
Hello bro! Is it possible to turn on auto broadcast after the end of the hour limit instagram?

**Comment by JRoy** [comment]
Just stream with the -i param.

This is an edge case that would be impractical to add

**Comment by be2clack** [comment]
> Just stream with the -i param.
> 
> This is an edge case that would be impractical to add

I do not understand. how to do ??

**Comment by JRoy** [comment]
`php goLive.php -i`

**Comment by be2clack** [comment]
> `php goLive.php -i`

when I start like this, after 10 seconds the broadcast is turned off

**Comment by be2clack** [comment]
obs stops broadcasting itself in 5-10 seconds

**Comment by be2clack** [comment]
> `php goLive.php -i`

obs stops broadcasting itself in 5-10 seconds
