### ISSUE TITLE
Trim Config Username and Password

### ISSUE THREAD

**Issue by gotmygat** [JRoy/InstagramLive-PHP#131]
Hey dude,

I wanted to reply to the thread you locked, I used the same password as the one I entered in the config file, but for some reason, it did not work until I tried the method you showed me. Is there a bug maybe?

**Comment by JRoy** [comment]
I could try trimming the input given to the script.

**Comment by gotmygat** [comment]
Perhaps, because I tried inputting the same username and password that I entered in cmd after I put the command you gave me in the previous post, and it worked there but not in the script. Do let us know when you get a chance to update it ! Thank you again

**Comment by JRoy** [comment]
Fixed probably in 1.6
