### ISSUE TITLE
How to enable comments to go through OBS and not CMD ?

### ISSUE THREAD

**Issue by gotmygat** [JRoy/InstagramLive-PHP#132]

**Comment by JRoy** [comment]
Use the `-o` param and run the script like `php goLive.php -o` to make the comments go into output.txt. Then just read that file in obs

**Comment by gotmygat** [comment]
How would I read the file in obs?

**Comment by gotmygat** [comment]
Also can I run multiple parameters? I am still having issues with the logging on? so I need to use -p and gotta now use -o
