### ISSUE TITLE
Comments with OBS Text file working, but how to get chat within OBS to integrate with stream?

### ISSUE THREAD

**Issue by gotmygat** [JRoy/InstagramLive-PHP#133]
I can successfully see chats happening on the CMD coming up into OBS as a text layer no problem, but what about getting OBS' in-app chat system to write back to the getlive.php script? So if I chat within OBS can I have that go out back to the PHP?

In another unrelated question, I did not want to spam your GitHub too much, but the measurements are off for the window from when I last used your script months ago. I realized that you have now incorporated a more smartphone-like screen ratio, but OBS doesn't seem to want to adjust my stream to the ratio of what you incorporated now. Any workaround for that?

**Comment by JRoy** [comment]
All this info is given in the documentation. Please read it. Additionally, I don't give support on OBS
