### ISSUE TITLE
web-remote control

### ISSUE THREAD

**Issue by be2clack** [JRoy/InstagramLive-PHP#135]
Can you make a FULL remote control for windows? for those who use a static ip address / or vps on windows?

**Comment by JRoy** [comment]
This isn't happening any time soon but I'll leave this opened

**Comment by zsvendo** [comment]
This is what you need to control over the web

**Comment by be2clack** [comment]
> This is what you need to control over the web

yes!

**Comment by JRoy** [comment]
Added in [1.8](https://github.com/JRoy/InstagramLive-PHP/releases/tag/1.8)

Run `php update.php` in your InstagramLive-PHP folder to update

Regards.
