### ISSUE TITLE
Error re-stream after one hour

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#138]
Dear Roy
Error v 1.6 after one hour 
Error While Creating Livestream: InstagramAPI\Response\CommentBroadcastResponse: This broadcast is already ended, your comment is not displayed.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.6
InstagramLive-PHP Flavor: beta
Instagram-API Version: dev-master#1598f2e3df05bea6cef89c9a6ec64c6167f1794
Operating System: WINNT
PHP Version: 7.3.3
PHP Runtime: cli
PHP Binary: C:\xampp\php\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Exception: InstagramAPI\Response\CommentBroadcastResponse: This broadcast is already ended, your comment is not displayed.
============END DUMP============

**Comment by JRoy** [comment]
This is throttling on part of Instagram, you should wait a few days for this to clear up.
