### ISSUE TITLE
DNS server not authoritative for zone

### ISSUE THREAD

**Issue by elno364** [JRoy/InstagramLive-PHP#139]
i followed this tutorial carefully: https://www.youtube.com/watch?v=NaX1Ge1Rthk
when I enter the command to go live, cmd gives me a message that reads: 

```
Loading InstagramLive-PHP v1.5.1...
Update: Outdated Instagram-API version detected, attempting to fix this for you. This may take a while...
DNS server not authoritative for zone.
Update: Finished! Exiting the script, please re-run the script now.
```
And then nothing happens. Any ideas what the problem could be?

**Comment by JRoy** [comment]
@elno364 [Please follow this tutorial](https://www.youtube.com/watch?v=J6lp8g3zQeE) instead of that one. But to fix this issue, you could probably change your dns provider. I suggest [1.1.1.1](https://1.1.1.1)

**Comment by elno364** [comment]
Thank you!
