### ISSUE TITLE
problem in streaming live with obs

### ISSUE THREAD

**Issue by natoordasht** [JRoy/InstagramLive-PHP#141]
php -f golive.php
Loading InstagramLive-PHP v1.5.1...
Logging into Instagram! Please wait as this can take up-to two minutes...
Error While Logging in to Instagram: InstagramAPI\Response\TimelineFeedResponse: Consent required.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.5.1
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#1598f2e3cdf05bea6cef89c9a6ec64c6167f1794
Operating System: WINNT
PHP Version: 7.3.4
PHP Runtime: cli
PHP Binary: C:\Users\Caligula\Desktop\instagram files\php\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
============END DUMP============

**Comment by be2clack** [comment]
Error While Logging in to Instagram ?

**Comment by JRoy** [comment]
Will be fixed in 1.6

**Comment by be2clack** [comment]
<img width="976" alt="Снимок экрана 2019-04-15 в 1 17 41" src="https://user-images.githubusercontent.com/1636306/56097936-70574000-5f1c-11e9-8df9-814e848968d6.png">
I have a problem. everything worked fine. and suddenly this

**Comment by be2clack** [comment]
> Will be fixed in 1.6

I have a problem. everything worked fine. and suddenly this

**Comment by be2clack** [comment]
> Will be fixed in 1.6

??????
