### ISSUE TITLE
Strange login activity emails when using script

### ISSUE THREAD

**Issue by tareeko** [JRoy/InstagramLive-PHP#142]
Whenever I go live, I get emails from Instagram telling me that I have logged in from random Android devices.

This includes the Samsung SM-G930F and the ZTE A2017U.

Any reason behind this?

**Comment by JRoy** [comment]
Yep, this is entirely normal. The API this script uses emulates the Android app and to do this it has to spoof an Android device. 

This is a list of all devices the API uses: https://github.com/mgp25/Instagram-API/blob/master/src/Devices/GoodDevices.php
