### ISSUE TITLE
I got some error

### ISSUE THREAD

**Issue by iwaskagHQ** [JRoy/InstagramLive-PHP#143]
Loading InstagramLive-PHP v1.6...
Logging into Instagram! Please wait as this can take up-to two minutes...
Error While Logging in to Instagram: Network: CURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.6
InstagramLive-PHP Flavor: beta
Instagram-API Version: dev-master#0a9d2b911203c55e3262bab0b8e9466feba7d5e0
Operating System: WINNT
PHP Version: 7.1.1
PHP Runtime: cli
PHP Binary: C:\AppServ\php7\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
============END DUMP============

**Comment by iwaskagHQ** [comment]
I am on PHP 7.1

**Comment by JRoy** [comment]
This is an issue with curl not having a valid CA file. You can fix this by following the instructions here: https://stackoverflow.com/a/34883260
