### ISSUE TITLE
Not start stream again after one hour

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#146]
Dear Roy

After stream has stoped due to instagram's one hour time limit, The new stream does not start and the same message is displayed and this is repeated in succession.
(please see [ this]( http://s8.picofile.com/file/8358400884/cover6.jpg))

what is the problem?

(There is no such problem with previous versions)

thanks a lot

**Comment by JRoy** [comment]
Oh shit, I think I know the issue

**Comment by JRoy** [comment]
Fixed in 1.6.1
