### ISSUE TITLE
No configs given

### ISSUE THREAD

**Issue by akhmed2001** [JRoy/InstagramLive-PHP#148]
Hi, can u say, how to fix it ? 
Error While Logging in to Instagram: InstagramAPI\Response\LauncherSyncResponse: No configs given.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.6.2
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#fbdca3a1d4889adca7237e7e3c95ad39657aa7c6
Operating System: Linux
PHP Version: 7.3.4
PHP Runtime: cli
PHP Binary: /data/data/com.termux/files/usr/bin/php
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
============END DUMP============

**Comment by zsvendo** [comment]
Same problem here

**Comment by akhmed2001** [comment]
Works after last update.

**Comment by JRoy** [comment]
Fixed this in 1.6.3

**Comment by zsvendo** [comment]
Version 1.6.3
Same mistake
Error While Logging in to Instagram: InstagramAPI \ Response \ LauncherSyncResponse: No configs given.

**Comment by zsvendo** [comment]
see the image
https://prnt.sc/nhotl9

**Comment by JRoy** [comment]
@zsvendo please do `composer update`

**Comment by zsvendo** [comment]
Ok, it worked.
