### ISSUE TITLE
It's possible? Automate

### ISSUE THREAD

**Issue by zsvendo** [JRoy/InstagramLive-PHP#149]
Is it possible to automate everything by php, without using command line?
Well I want to run the amazon server and I do not want to go there to run command line, I wanted to use Apache, something like that?

**Comment by JRoy** [comment]
There's a lot of automation available, if you run `php goLive.php --help` you can see a lot of options 

Regards

**Comment by zsvendo** [comment]
I want to automate in php and not use command line

**Comment by JRoy** [comment]
You can't use a webserver to host this if that's what you mean. A website would create issues with the stream not working

**Comment by zsvendo** [comment]
but only to give commands is not possible? Start, Stop, User and Password?
