### ISSUE TITLE
Add Comment Pinning

### ISSUE THREAD

**Issue by penteseter123** [JRoy/InstagramLive-PHP#15]
how to display pinned on Instagram comments with php live programs thanks help me for coding and develop 

![image](https://user-images.githubusercontent.com/35046129/44000646-2aa6c704-9e4e-11e8-8cd0-0a9a7fbd38fa.png)

**Comment by JRoy** [comment]
Adding in v0.5 with new async comments system in #4

**Comment by JRoy** [comment]
Added in v0.5-BETA-2

**Comment by penteseter123** [comment]
Dear Jroy
Thanks Closes in Pinned Instagram Success Now Can it comment and reply
comments in instagram

Best Regards
Thanks
