### ISSUE TITLE
Resolution/Zooming Issue

### ISSUE THREAD

**Issue by mentalpoodle** [JRoy/InstagramLive-PHP#155]
Hello, thanks for your amazing project, it works!! :) I'm on windows 10 1809. I have a problem, I've set OBS to stream at 9:16 1080x1920px, but when I check the stream on instagram, it's a bit blurry (looks more like 720p or even 480p?), and it's a bit "zoomed-in" compared to my preview on OBS. Like if you zoomed it by 15%. Also, a minor issue, when I start the stream, it says "OBS not detected", but OBS works and controls the stream with no problems. Any ideas to resolve the blurriness? (Please consider that I'm a complete programming illitterate, so the fact that this even works means you made an amazing tutorial!!!).

**Comment by JRoy** [comment]
1080x1794 resolution should fix your problem

**Comment by mentalpoodle** [comment]
Got it, will try it this evening. Thanks a lot!
