### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mettoal** [JRoy/InstagramLive-PHP#157]
hi ı have problem obs studio ( could not access the specified channel or stream key, please double-check your stream key. if it is correct, there may be a problem connecting to the server. ) do u know this problem

**Comment by itsDJDeem** [comment]
Having this same issue. I've been trying to find a fix

**Comment by mahdialmasi313** [comment]
Please join the issues : [https://github.com/JRoy/InstagramLive-PHP/issues/156](https://github.com/JRoy/InstagramLive-PHP/issues/156)

**Comment by JRoy** [comment]
Duplicate of #156, please move discussion to there.
