### ISSUE TITLE
Terrible live quality

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#16]
@JRoy When I'm streaming with PC, quality is good.
But when I'm streaming from laptop, the quality of live is terrible.
This problem only when streaming to Instagram from laptop. (The quality of streaming to other sites is very good from laptop)

**Comment by JRoy** [comment]
Instagram

**Comment by JRoy** [comment]
Instagram compresses the shit out of live video this is not a problem of my script but rather a feature of Instagram
