### ISSUE TITLE
Aspect Ratio Support

### ISSUE THREAD

**Issue by njokusomto** [JRoy/InstagramLive-PHP#160]
It would be nice to be able to control the aspect ratio or have it contained within the viewport.
Right now, the video just fills the screen.

Great job, BTW!!

**Comment by JRoy** [comment]
Could you please elaborate, I don't know what you mean by control the aspect ratio. In OBS? In Instagram? and what do you mean by viewport?

**Comment by njokusomto** [comment]
Okay, here's what I mean...
When I started streaming, I noticed the video was in vertical 16:9 aspect ratio (720x1280).
Is it possible to lock this down so it stays as 1280x720 instead?

Right now, the video covers my entire screen. Is it possible to contain the video within the viewport?
Please visit the link below to see what I mean.
https://imgur.com/a/e3APZPx

Can it be like the picture in the "AFTER" area?

Thanks!

**Comment by JRoy** [comment]
Instagrma is a vertical app and only allows streaming in vertical format, you may need to tweak your settings in obs to ensure your content is displayed in the correct way.

Cheers.
