### ISSUE TITLE
Error after star streaming can´t send commands

### ISSUE THREAD

**Issue by denialhost** [JRoy/InstagramLive-PHP#161]
Starting Stream...
Command Line: Windows/macOS Detected! A new console will open for command input and this will become command/like output.
PHP Fatal error:  Uncaught Error: Call to undefined method InstagramAPI\Request\Live::getJoinRequestCounts() in C:\InstagramLive-PHP-master\goLive.php:624
Stack trace:
#0 C:\InstagramLive-PHP-master\goLive.php(291): beginListener(Object(ExtendedInstagram), '180020862822153...', 'rtmps://live-up...', '180020862822153...', true, false, Object(ObsHelper), 0, NULL, Array, 0, 0, -1, -1)
#1 C:\InstagramLive-PHP-master\goLive.php(126): main(true, Object(ObsHelper), 0, NULL, Array)
#2 {main}
  thrown in C:\InstagramLive-PHP-master\goLive.php on line 624

Fatal error: Uncaught Error: Call to undefined method InstagramAPI\Request\Live::getJoinRequestCounts() in C:\InstagramLive-PHP-master\goLive.php:624
Stack trace:
#0 C:\InstagramLive-PHP-master\goLive.php(291): beginListener(Object(ExtendedInstagram), '180020862822153...', 'rtmps://live-up...', '180020862822153...', true, false, Object(ObsHelper), 0, NULL, Array, 0, 0, -1, -1)
#1 C:\InstagramLive-PHP-master\goLive.php(126): main(true, Object(ObsHelper), 0, NULL, Array)
#2 {main}
  thrown in C:\InstagramLive-PHP-master\goLive.php on line 624

**Comment by JRoy** [comment]
Delete your `composer.json` file and your `vendor/` folder and then run `php update.php` 

**Please** check the readme on proper update procedure as to update all you need to do is run the update.php file.

Cheers.
