### ISSUE TITLE
Video Hitching on High Demand

### ISSUE THREAD

**Issue by JDepa** [JRoy/InstagramLive-PHP#169]
Hey JRoy,

Attempting to use this tool to facilitate a live stream which has between 50-500 viewers depending on time of stream, and we're finding that at low demand (low like count, not many comments, low viewership) we are steaming fine, but on high-viewership/high-engagement streams there are a few half-second "hitches" where the stream will pause and resume.

This isn't visible on OBS when streaming, but eventually the Instagram Live video will fall pretty far behind (about a minute behind per ten minutes streamed). 

Not sure if this is due to load from the number of comments your script may be processing, or if it is likely to be on the instagram server-side?

**Comment by JRoy** [comment]
This is a known bug, yet it will take some research to figure out what I can do on my end to mitigate this.

**Comment by johnatan22** [comment]
my broadcast hit 8500 simultaneous people and I had no problem

**Comment by JRoy** [comment]
For people having this problem, broadcast in 24fps with a bitrate ranging from 1000-5000
