### ISSUE TITLE
Connection Errors

### ISSUE THREAD

**Issue by mws84** [JRoy/InstagramLive-PHP#173]
Firewall is turned off, everyone using our Wi-FI can go live so the IP is not banned. Please advise.

Additional suggestion, provide stream URL and Key like in previous versions, the automation is not working out well.

Output:

E:\IG_STREAM>php goLive.php -i -d --obs --use-rmtps
Loading InstagramLive-PHP v1.7.2...
PHP Warning:  Use of undefined constant OBS_MODIFY_SETTINGS - assumed 'OBS_MODIFY_SETTINGS' (this will throw an Error in a future version of PHP) in E:\IG_STREAM\goLive.php on line 129
PHP Warning:  Use of undefined constant OBS_CUSTOM_PATH - assumed 'OBS_CUSTOM_PATH' (this will throw an Error in a future version of PHP) in E:\IG_STREAM\obs.php on line 46
OBS Integration: Multi-Profile environment detected! Please select your current OBS profile.
[0] - Untitled
[1] - tyler
OBS Integration: Type your Profile ID from the above selection...
> 0
Logging into Instagram! Please wait as this can take up-to two minutes...
Logged In!
PHP Warning:  Use of undefined constant STREAM_RECOVERY - assumed 'STREAM_RECOVERY' (this will throw an Error in a future version of PHP) in E:\IG_STREAM\utils.php on line 209
PHP Warning:  Use of undefined constant STREAM_RECOVERY - assumed 'STREAM_RECOVERY' (this will throw an Error in a future version of PHP) in E:\IG_STREAM\utils.php on line 209
Creating Livestream...
PHP Warning:  Use of undefined constant OBS_X - assumed 'OBS_X' (this will throw an Error in a future version of PHP) in E:\IG_STREAM\goLive.php on line 175
PHP Warning:  Use of undefined constant OBS_Y - assumed 'OBS_Y' (this will throw an Error in a future version of PHP) in E:\IG_STREAM\goLive.php on line 175
Error While Creating Livestream: No response from server. Either a connection or configuration error.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.7.2
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#87b3d4960dfd2768385de4c7eeb12492124d46cd
Operating System: WINNT
PHP Version: 7.3.1
PHP Runtime: cli
PHP Binary: C:\php-7\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Exception: No response from server. Either a connection or configuration error.
============END DUMP============

**Comment by JRoy** [comment]
Please properly install the script, delete all the files except `update.php` and run it.
