### ISSUE TITLE
Error While Creating Livestream

### ISSUE THREAD

**Issue by Cabr0** [JRoy/InstagramLive-PHP#174]
Hey JRoy,

I tried going live today but had a problem with the stream. Maybe an Instagram update?

Here's the error message.

> Loading InstagramLive-PHP v1.7.2...
> Logging into Instagram! Please wait as this can take up-to two minutes...
> Logged In!
> Recovery Detected, Restarting Stream...
> **Please** update your current Stream URL if you have one in your current streaming program. A recent update has made the old url not work so please use the one below!
> ================================ Stream URL ================================
> rtmps://live-upload.instagram.com:443/rtmp/
> ================================ Stream URL ================================
> ======================== Current Stream Key ========================
> 18076533568016148?s_efg=eyJxZV9ncm91cHMiOnsiaWdfbGl2ZV9lbmFibGVfcG9wX3ByaW1pbmciOnsiZW5hYmxlZCI6InRydWUifSwiaWdfbG93X2xhdGVuY3lfcHJvZHVjdGlvbl91bml2ZXJzZSI6eyJlbmFibGVkIjoidHJ1ZSJ9fX0%3D&s_vt=ig&a=AbzQH7ohDKqQJuIS
> ======================== Current Stream Key ========================
> 
> **Please** update your current Stream URL if you have one in your current streaming program. A recent update has made the old url not work so please use the one below!
> Command Line: Windows/macOS Detected! A new console will open for command input and this will become command/like output.
> Error While Creating Livestream: InstagramAPI\Response\BroadcastCommentsResponse: Sorry, this media has been deleted.
> ===========BEGIN DUMP===========
> InstagramLive-PHP Version: 1.7.2
> InstagramLive-PHP Flavor: stable
> Instagram-API Version: dev-master#87b3d4960dfd2768385de4c7eeb12492124d46cd
> Operating System: WINNT
> PHP Version: 7.3.5
> PHP Runtime: cli
> PHP Binary: C:\xampp\php\php.exe
> Bypassing OS-Check: false
> Composer Lock: true
> Vendor Folder: true
> Exception: InstagramAPI\Response\BroadcastCommentsResponse: Sorry, this media has been deleted.

Thank you for your time.

![image](https://user-images.githubusercontent.com/52027569/59828310-018ecc80-933b-11e9-858b-e5169ea93b71.png)

**Comment by JRoy** [comment]
This appears to be an issue with stream recoveries, I fixed this in 60abf9c2d36a0742b16a558149bc608add8b3488 on the 1.8 development branch.

For the time being, you can delete the `backup.json` file to fix your problem.
