### ISSUE TITLE
2FA doesn't have method selection

### ISSUE THREAD

**Issue by chexburger** [JRoy/InstagramLive-PHP#175]
I've tried about 4 times along with disabling my 2fa but it continually asks for a 2fa code. I've entered the one I've gotten through Authy with no success however the same Authy code works for logging in through anything else.
If I use an account that never had 2fa, it works fine.

![image](https://user-images.githubusercontent.com/15860911/60139726-3f8d5580-976c-11e9-8391-7fe1932c1419.png)

**Comment by JRoy** [comment]
1.8 will have a better solution to this

**Comment by chexburger** [comment]
Alright

**Comment by JRoy** [comment]
Fixed in [1.8](https://github.com/JRoy/InstagramLive-PHP/releases/tag/1.8)

Run `php update.php` in your InstagramLive-PHP folder to update

Regards.
