### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by proggi03** [JRoy/InstagramLive-PHP#176]
When i start the the script, open obs and click on start stream i become a error "Failed to connect to server" every time I start the script i become the same Stream URL und Stream Key.

**Comment by JRoy** [comment]
Hello! Can you please run the script like `php goLive.php --debug` and share the output here. (Make sure to censor out username and password)

**Comment by proggi03** [comment]
Here is the log [log.txt](https://github.com/JRoy/InstagramLive-PHP/files/3342030/log.txt) the account is a test account for that

**Comment by JRoy** [comment]
Fixed in [1.8](https://github.com/JRoy/InstagramLive-PHP/releases/tag/1.8)

Run `php update.php` in your InstagramLive-PHP folder to update

Regards.

**Comment by proggi03** [comment]
In update  1.8 I have the same error.

**Comment by JRoy** [comment]
Try reinstalling the script

**Comment by proggi03** [comment]
Same error.
