### ISSUE TITLE
access to control panel

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#179]
Dear Roy
How can i access to control panel? when i enter 127.0.0.1, I see  first page of xampp (XAMPP Apache + MariaDB + PHP + Perl) Even after run php goLive.php --web.

thanks a lot

**Comment by ahmadd110** [comment]
On another PC, I can access the control panel
Is it because of the installation iis on port 80  and I've run xampp on port 90?

**Comment by JRoy** [comment]
Hi, you can change the port of the control panel in the config.

Change the `WEB_PORT` value and then visit `127.0.0.1:PORT` (where "PORT") is the new port you've set

**Comment by ahmadd110** [comment]
thanks, it worked
but But the following message is displayed


"Waiting for livestream...
InstagramLive-PHP Console is waiting for your stream to start...
Please make sure you started this console with your goLive.php script and that the goLive.php script is running in --web mode"

**Comment by JRoy** [comment]
That's a known bug, will be fixed in the next version
