### ISSUE TITLE
The program just broke

### ISSUE THREAD

**Issue by arthuro555** [JRoy/InstagramLive-PHP#181]
I was using it to stream when it suddenly just shut down like it crashed but didn't do any crash dump or anything. The stream didn't stop and The program isn't running in the background, and the stream is unstoppable. When I ran goLive.php again, it returned:

```
Loading InstagramLive-PHP v1.8...
Commands: Registering commands...
Commands: Registered commands!
Login: Starting Instagram logon, please wait...
Login: Successfully logged in!
PHP Fatal error:  Uncaught TypeError: Return value of Utils::getRecovery() must be of the type array, null returned in D:\Users\pc\Documents\InstagramLive-PHP\utils.php:200
Stack trace:
#0 D:\Users\pc\Documents\InstagramLive-PHP\goLive.php(303): Utils::getRecovery()
#1 D:\Users\pc\Documents\InstagramLive-PHP\goLive.php(257): preparationFlow(true, Object(ObsHelper), Array, Array, 0, NULL)
#2 {main}
  thrown in D:\Users\pc\Documents\InstagramLive-PHP\utils.php on line 200

Fatal error: Uncaught TypeError: Return value of Utils::getRecovery() must be of the type array, null returned in D:\Users\pc\Documents\InstagramLive-PHP\utils.php:200
Stack trace:
#0 D:\Users\pc\Documents\InstagramLive-PHP\goLive.php(303): Utils::getRecovery()
#1 D:\Users\pc\Documents\InstagramLive-PHP\goLive.php(257): preparationFlow(true, Object(ObsHelper), Array, Array, 0, NULL)
#2 {main}
  thrown in D:\Users\pc\Documents\InstagramLive-PHP\utils.php on line 200
```

I'm using the latest version on windows 10.

**Comment by JRoy** [comment]
You're running php5, please use php 7

**Comment by arthuro555** [comment]
I was pretty sure I already have php7. Anyways I fixed it by starting a new stream from my phone, what disabled the previous stream and deleting backup.json wich was corrupted. Now it works fine.

**Comment by JRoy** [comment]
Okay, I'll look into recovery files again to try and prevent this from happening again

**Comment by kaiobonfim** [comment]
I have the same issue, using php 7, still couldn't fix it :(
Any suggestions?

**Comment by arthuro555** [comment]
Reinstall it ?

From : kaiobonfim<mailto:notifications@github.com>
Date : sunday 25 august 2019 01:00
To : JRoy/InstagramLive-PHP<mailto:InstagramLive-PHP@noreply.github.com>
Cc : Arthur Pacaud<mailto:arthur.pacaud@hotmail.fr>; Author<mailto:author@noreply.github.com>
Object :Re: [JRoy/InstagramLive-PHP] The program just broke (#181)


I have the same issue, using php 7, still couldn't fix it :(
Any suggestions?
