### ISSUE TITLE
Error while logging into Instagram: Network: CURL error 60: SSL 

### ISSUE THREAD

**Issue by L7n111** [JRoy/InstagramLive-PHP#183]
C:\xampp\htdocs\0>php goLive.php
Loading InstagramLive-PHP v1.8...
Commands: Registering commands...
Commands: Registered commands!
Login: Starting Instagram logon, please wait...
Error while logging into Instagram: Network: CURL error 60: SSL certificate prob
lem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/l
ibcurl-errors.html).
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.8
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#0fa48d45ce103b5a107f90fe5c403c1a2bb7e8f2
Operating System: WINNT
PHP Version: 7.2.10
PHP Runtime: cli
PHP Binary: C:\wamp647\bin\php\php7.2.10\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
============END DUMP============

i dont have VPN  i did setup the cert.pem file in php.ini 

i turn off my firewall Same Problem Every time

i am Win7 64Bit 

i am using xampp

**Comment by JRoy** [comment]
This is an issue with curl not having a valid CA file. You can fix this by following the instructions here: https://stackoverflow.com/a/34883260
