### ISSUE TITLE
OBS not accepting stream key

### ISSUE THREAD

**Issue by bptestinsta** [JRoy/InstagramLive-PHP#184]
Hi Jroy, Once I try and enter the stream key into OBS and start streaming a message in OBS comes up saying 'could not access the specified channel or stream key' 

I have just updated OBS so im not sure if that affected it? Do you have any suggestions?

**Comment by JRoy** [comment]
Make sure you're using rtmpz

**Comment by bptestinsta** [comment]
It had something to do with the URL link. The original link I was using wasn’t a secure link apparently. Do you have any suggestions for secure links? 

Thank you so much for your help!
