### ISSUE TITLE
Auto Kill Web Server

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#185]
Dear  JRoy
First, thank you for these Nice codes.
Is it possible to automatically exit cmd after end live streaming from web-console and do not need to manually exit?
thanks

**Comment by JRoy** [comment]
This is planned for a future release

**Comment by ahmadd110** [comment]
Has auto kill web server been added in v1.9?

**Comment by JRoy** [comment]
Yep, stable release will be tonight

**Comment by njokusomto** [comment]
Awesome stuff.
Looking forward to the update!

**Comment by ahmadd110** [comment]
excellent
