### ISSUE TITLE
parse error on goLive.php line 924

### ISSUE THREAD

**Issue by bulkdev** [JRoy/InstagramLive-PHP#188]
Parse error: parse error, expecting `'{'' in /Users/test/Desktop/InstagramLive-PHP-master/goLive.php on line 924

**Comment by bulkdev** [comment]
after running php -f goLive.php

**Comment by JRoy** [comment]
Make sure you at least have php 7 and just use `php goLive.php`

**Comment by bulkdev** [comment]
yea i got php 7 and i tried with just that too
