### ISSUE TITLE
Not working properly automatic web console closing

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#192]
Dear Roy

In v1.9.1, automatic web console closing works for last web console (CMD) but the previous ones remain and are not closed.
See [this](http://s3.picofile.com/file/8373272026/livet.png)
thanks

**Comment by JRoy** [comment]
What arguments are you using?

**Comment by ahmadd110** [comment]
php goLive.php -i -a -o --web --no-obs --dcomments --bypass-pause --auto-pin=Hello

**Comment by AnitaPazhohesh** [comment]
Hi guys,
Can you please let me know how can I use the 1 hour live limit bypass
command argument in php version 1.9.1 to keep the live stream after 1 hour?
I need to go live for 3 hours on Instagram with no cutoff or interruption.
Thanks much.
Anita

**Comment by JRoy** [comment]
Fixed in 2.0
