### ISSUE TITLE
Account reminder

### ISSUE THREAD

**Issue by lud4l** [JRoy/InstagramLive-PHP#193]
Hello JRoy!

Do you think it should be possible to see the account where you log at when you start the script?

Actually we see : "Login : successfully logged in !"
Could we see : "Login : successfully logged in to 'IG_USERNAME' !" ?

That would be useful :)

What do you think about that ?

Thanks for your work on this tool!

**Comment by JRoy** [comment]
Sure thing, can add in the next version!

**Comment by lud4l** [comment]
Thanks!

**Comment by JRoy** [comment]
Added in 2.0
