### ISSUE TITLE
getting error in config.php

### ISSUE THREAD

**Issue by BOBKADAM** [JRoy/InstagramLive-PHP#195]
Below is the error I am getting in the terminal

pankits-MacBook-Pro:Instagram1.4 bhavesh$ php golive.php
PHP Parse error:  syntax error, unexpected '@', expecting ')' in /Users/pankit/Desktop/Instagram1.4/config.php on line 4

Parse error: syntax error, unexpected '@', expecting ')' in /Users/pankit/Desktop/Instagram1.4/config.php on line 4

![Screen Shot 2019-09-27 at 11 51 28 AM](https://user-images.githubusercontent.com/55616213/65746773-4cc83080-e11d-11e9-88db-4366b3569f43.png)

**Comment by BOBKADAM** [comment]
Can you guide me about instagram  for MAC book?
Like you have done for windows.

**Comment by JRoy** [comment]
You need php 7
