### ISSUE TITLE
Error on commands while streaming

### ISSUE THREAD

**Issue by lud4l** [JRoy/InstagramLive-PHP#196]
Hello!

I have a strange issue. When streaming, I can't use the in live commands, here is what my console is saying :

> Starting the in live console, there some error but the live works :
> Command Line: Processing commands...
> Command Line: Fetching available commands...
> PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/XXXX/instagramlive/commandLine.php on line 13
> 
> Warning: count(): Parameter must be an array or an object that implements Countable in /Users/freecaster/instagramlive/commandLine.php on line 13
> Command Line: Fetched 0 commands!
> Command Line: Mapping Commands...
> PHP Warning:  Invalid argument supplied for foreach() in /Users/XXXX/instagramlive/commandLine.php on line 16
> 
> Warning: Invalid argument supplied for foreach() in /Users/XXXX/instagramlive/commandLine.php on line 16
> Command Line: Mapped Commands!
> Command Line: Finished processing commands!
> Command Line: Please wait while the stream starts...
> Command Line: Ready! Type "help" for help.

Then, I can't use commands :

> > dcomments
> Command Line: Invalid Command. Type "help" for help!
> 

> > help
> Commands:
> help - Displays this message

only "stop" works :

> > stop
> Would you like to keep the stream archived for 24 hours? Type "yes" to do so or anything else to not.

What should I do ?

**Comment by JRoy** [comment]
Could you please do `php goLive.php --dump` and share the output. Additionally can you do `php goLive.php --dumpCmds` and share the output.

Thanks!

**Comment by Michasul** [comment]
Hey,

Same issue :

MacBook-Pro-de-Michael:IGLIVE michaelsulman$ php goLive.php --dump
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.9.2.1
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#d3bed42be75bd0be2d40de5ba8033f1bbc515df7
Operating System: Darwin
PHP Version: 7.1.23
PHP Runtime: cli
PHP Binary: /usr/bin/php
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
============END DUMP============
MacBook-Pro-de-Michael:IGLIVE michaelsulman$ 



MacBook-Pro-de-Michael:IGLIVE michaelsulman$ php goLive.php --dumpCmds
["{\"name\":\"ecomments\",\"description\":\"Enables comments\",\"argument\":\"\",\"auto\":true}","{\"name\":\"dcomments\",\"description\":\"Disables comments\",\"argument\":\"\",\"auto\":true}","{\"name\":\"end\",\"description\":\"Ends the livestream\",\"argument\":\"(yes\\\/no) Archive Stream\",\"auto\":true}","{\"name\":\"pin\",\"description\":\"Pins a comment\",\"argument\":\"Comment ID\",\"auto\":false}","{\"name\":\"unpin\",\"description\":\"Unpins the currently pinned comment\",\"argument\":\"\",\"auto\":true}","{\"name\":\"pinned\",\"description\":\"Displays the currently pinned comment\",\"argument\":\"\",\"auto\":true}","{\"name\":\"comment\",\"description\":\"Posts a comment on the stream\",\"argument\":\"Comment Text\",\"auto\":true}","{\"name\":\"url\",\"description\":\"Displays the stream url\",\"argument\":\"\",\"auto\":true}","{\"name\":\"key\",\"description\":\"Displays the stream key\",\"argument\":\"\",\"auto\":true}","{\"name\":\"info\",\"description\":\"Displays general info about the stream\",\"argument\":\"\",\"auto\":true}","{\"name\":\"viewers\",\"description\":\"Displays the list of people viewing the stream\",\"argument\":\"\",\"auto\":true}","{\"name\":\"questions\",\"description\":\"Displays all questions from the stream\",\"argument\":\"\",\"auto\":true}","{\"name\":\"showquestion\",\"description\":\"Shows a question on the stream\",\"argument\":\"Question ID\",\"auto\":true}","{\"name\":\"hidequestion\",\"description\":\"Hides the currently hidden question from the stream\",\"argument\":\"\",\"auto\":true}","{\"name\":\"wave\",\"description\":\"Waves at a user who has joined the stream\",\"argument\":\"User ID\",\"auto\":true}","{\"name\":\"block\",\"description\":\"Blocks a user from your account\",\"argument\":\"User ID\",\"auto\":true}"]MacBook-Pro-de-Michael:IGLIVE michaelsulman$

**Comment by JRoy** [comment]
Fixed in 2.0

**Comment by waleedhom** [comment]
i have version 2.0 i download it now and same problem but if i start command with 
php goLive.php -dcomments 

is working but in live i cannot do any commands

how to fix this .

**Comment by mano1** [comment]
In case it's helpful, I have the same problem. I tested with several PHP version, and builds. Thanks for addressing and letting us know! Take care
-mano

PS: amazing project, thank you for doing it.
