### ISSUE TITLE
How to delete / hide a single user comment?

### ISSUE THREAD

**Issue by trx222** [JRoy/InstagramLive-PHP#199]
Is it possible to delete a comment on a live stream, maybe because its against law or offend someone? If so, then how - I couldn't find a method for this. Thank you for the great lib!

**Comment by JRoy** [comment]
I'll see if it's possible

**Comment by trx222** [comment]
As additional info: In live stream from instagram app I also do not find a "delete" Button (on iOS) ... But I have the possibility to "Hide livestream for this user" ... If there is no way to delete/hide comments then it also would help if I have the function for hiding the stream to user.

Again Thanks for all!

**Comment by JRoy** [comment]
Sorry for the delay, I didn't find a way to delete comments sadly but I did see the hide livestream from the user. 

As for hiding the stream, I've added this in 2.1 :)
