### ISSUE TITLE
Please make a video

### ISSUE THREAD

**Issue by RNSPage** [JRoy/InstagramLive-PHP#2]
Hey Jroy, it would be nice if you can make a video on this
I will pay you if you can teach me on the composer part and other parts
 I'm a beginner on coding

**Comment by JRoy** [comment]
So a video on how to set this up?

**Comment by RNSPage** [comment]
Yes a video on how to set this up woukd be very helpful

**Comment by RNSPage** [comment]
Will you post the video on youtube or just link it too me?

**Comment by JRoy** [comment]
I'll make the video on YouTube and link it here

**Comment by JRoy** [comment]
Video tutorial is here: https://www.youtube.com/watch?v=mZfzFNZSuQc

**Comment by RNSPage** [comment]
For some reason i keep getting this playback. When i click on the
livestream everything is clear for split second but then this happens.
I attached the screenshot below

**Comment by JRoy** [comment]
I did not get the Screenshot try sending it through GitHub instead of email

**Comment by RNSPage** [comment]
Hey josh
I fixed it the problem it was becuase of the resolution it was too high in
obs.
The canvas base was fine.
It was just the resolution that messed it up.

**Comment by JRoy** [comment]
Ah okay perfect! Glad you can use it now!
