### ISSUE TITLE
Erro in Web 

### ISSUE THREAD

**Issue by paulocauca** [JRoy/InstagramLive-PHP#203]
Hi, 
I'm having a problem start `php goLive.php -web ` . The page open but I'm receiving an error :  `/tick - No such file or directory`. The web page doesn't respond any commands.

Is it need create another additional directory ?

Thank you for helping

**Comment by JRoy** [comment]
You must have a webserver running separate from the script, change the port in the config.

Regards.

**Comment by paulocauca** [comment]
Good ! It's works when a call `/usr/bin/php -S 127.0.0.1:8080 /liveproject/webServer.php`


Thank you for help me and congratulations for this project :-)
