### ISSUE TITLE
error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by arashhesni** [JRoy/InstagramLive-PHP#210]
how can i fix it?

**Comment by JRoy** [comment]
This is an issue with curl not having a valid CA file. You can fix this by following the instructions here: https://stackoverflow.com/a/34883260

**Comment by arashhesni** [comment]
i've downloaded the cacert.pem and placed it in the directory ,restarted my wamp server
still the same error!
