### ISSUE TITLE
Outdated Instagram-API version detected. Attempting a fix...

### ISSUE THREAD

**Issue by romulofuzo** [JRoy/InstagramLive-PHP#212]
PS C:\Program Files (x86)\obs-studio\LIVE INSTAGRAM\InstagramLive-PHP-2.1> php golive.php
Loading InstagramLive-PHP v2.1-stable (67)...
Update: Outdated Instagram-API version detected. Attempting a fix...
Update: Update Installed! Please re-run the script.

Tried updating, redownloading the files, still, same error.

Can't go live, keeps trying do fix the API, but it doesn't.

Can someone help me?

**Comment by JRoy** [comment]
Please run `php update.php`

**Comment by romulofuzo** [comment]
![image](https://user-images.githubusercontent.com/58052699/70662956-12632f80-1c46-11ea-8fdd-ac894069747f.png)

Like i said, i tried updating, redownloading the files, still, same error.

Can someone help me?

**Comment by JRoy** [comment]
Delete all the files but the update.php file then try running it again

**Comment by romulofuzo** [comment]
![image](https://user-images.githubusercontent.com/58052699/70667558-f4023180-1c4f-11ea-8981-d4bd54e04712.png)
Something happened, but now there is a problem with Composer.

**Comment by JRoy** [comment]
@romulofuzo try redownloading the update.php file, it should work now :))
