### ISSUE TITLE
Feature: Restart stream when streamlimit passen

### ISSUE THREAD

**Issue by MauriceNorden** [JRoy/InstagramLive-PHP#213]
Hello,

I really want to stream longer than an hour.
Can u inplement a feature that automaticaly makes a new instagram stream after 1 hour has passed?

Maurice Norden,

**Comment by JRoy** [comment]
Here's a list of command line arguments:
https://github.com/JRoy/InstagramLive-PHP/wiki/Command-Line-Arguments

Look for infinite stream.
