### ISSUE TITLE
Archived Live video not work

### ISSUE THREAD

**Issue by Bertisc** [JRoy/InstagramLive-PHP#25]
Hi! Amazing job. This is my problem. When I send the Stop command the script ask me if I want to archive my live video the next 24h. I send "yes". The script tell me all's fine and the video is archived but when I loggin into my account on my smartphone there's no live video saved.

**Comment by JRoy** [comment]
Hi, can you please verify that you are actually streaming and not leaving the stream content blank

**Comment by Bertisc** [comment]
Yes, I do streaming using videos and images with OBS. I watched my live videos with other mobile to check all works, and the streamings worked fine. Not archived error ocurred every time with differents accounts (I was testing) .

**Comment by JRoy** [comment]
@Bertisc when did you install the script and what operating system do you use?

**Comment by skt1dev** [comment]
I don't think it's a bug. Make sure your OBS resolution is set to 720x1280px
I had the same problem, and the livestream replays were available only in IOS. I changed the resolution and that solved it.
By the way, thanks for this JRoy, I'm having so much fun with my livestreams. It's amazing to have OBS for instagram. So grateful!

**Comment by JRoy** [comment]
Glad you enjoy the script @skt1dev 😄

@Bertisc: Also that as well, make sure you OBS resolution is 720x1280 as Instagram will sometimes reject other resolutions.

**Comment by Bertisc** [comment]
Thanks! I will try @skt1dev @JRoy 
By the way, I'm using the lastest version on a Windows 10

**Comment by Bertisc** [comment]
@skt1dev @JRoy Yes, it works. Thanks again and great job dude!
