### ISSUE TITLE
Not able to see live

### ISSUE THREAD

**Issue by dato309** [JRoy/InstagramLive-PHP#3]
Not able to see live stream under the Instagram account. Although the archived Story does become available as soon as live is stopped.

**Comment by JRoy** [comment]
If you're trying to view it from your own account you may not he able to

**Comment by AnitaPazhohesh** [comment]
Hi Josh,
I’m using Instagram Live PHP and I’m wondering if we can run Live for more than an hour and longer with no interruption by making some changes on php files?! I noticed one Persian tv channel is Live 24/7 on Instagram! Please advise.
Instagram.com/manotoofficial

Thanks much.
Anita

**Comment by JRoy** [comment]
@AnitaPazhohesh yea you could have the script wait 1hr to reset the cycle of creating a new broadcast. Basically you would just have to restart the script every hour.

**Comment by AnitaPazhohesh** [comment]
Thanks Josh for the reply but could you please let me know how to reset the script for continues live without interruption? I’m new on this!
Anita

**Comment by AnitaPazhohesh** [comment]
I tried to start a new live broadcast before the current one ends to run live without interruption but once I create a new script the current live ends!

**Comment by JRoy** [comment]
@AnitaPazhohesh does the live stream actually stop working after an hour? Have you tried just keeping it going?

**Comment by AnitaPazhohesh** [comment]
Yes, if I don’t send the STOP command by myself, live video stops automatically by Instagram. What I want to do is to continue streaming live beyond the 1 hour limit with no interruption in between just like what the “Manotoofficial” tv does 24/7. Do you have any idea how? I’m sure there should be a way that the above tv channel use.
Thanks!
Anita

**Comment by AnitaPazhohesh** [comment]
I’m sure there should be a way for continuous live that “Manotoofficial” use for their 24/7 uninterrupted live on Instagram. They probably use your PHP with some modifications to ignore the 1 hour time limit or maybe they did something that the script resets after every hour of live streaming!
