### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by hasanitman** [JRoy/InstagramLive-PHP#30]
Hello dear
we have problem with login to instagram (maybe filtered in my country)
how can i add proxy to this script?

thank for your answer

**Comment by JRoy** [comment]
I will not be supporting proxies, sorry

**Comment by hasanitman** [comment]
Hello again
I have proxy server, but i dont know where should i put it
Instagram api support proxy,
Do you know how to use it?
Thanks

**Comment by JRoy** [comment]
@hasanitman: as I've mentioned I will not support this, sorry
