### ISSUE TITLE
Live stream Disconnecting

### ISSUE THREAD

**Issue by hasanitman** [JRoy/InstagramLive-PHP#31]
Hello
sorry for much question
i use this script, after 1 hour the live stream disconnected, i afraid it's instagram limitation
if yes, how can i save stream in archive after disconneting

thanks

**Comment by hasanitman** [comment]
how should we do that?

i now install it on windows server

thanks

**Comment by JRoy** [comment]
I will see if I can add this in a future release

**Comment by hasanitman** [comment]
thanks
i have error while i run script on windows with xamp server

PHP Catchable fatal error:  Argument 2 passed to beginListener() must be an instance of string, string given, called in C:\xampp\htdocs\live\goLive.php on line 90 and defined in C:\xampp\htdocs\live\goLive.php on line 114

Catchable fatal error: Argument 2 passed to beginListener() must be an instance of string, string given, called in C:\xampp\htdocs\live\goLive.php on line 90 and defined in C:\xampp\htdocs\live\goLive.php on line 114

can u help me ?
thank you again

**Comment by JRoy** [comment]
@hasanitman yeah you made that in #32 and that will be fixed in 0.6 which is coming out today

**Comment by hasanitman** [comment]
i have online streaming after about 2 hours from now :)
can u fix it?
plz say yes 👍

**Comment by hasanitman** [comment]
if i use php 5, the problem not solved ?

**Comment by JRoy** [comment]
@hasanitman php7 is required

**Comment by hasanitman** [comment]
ok, then can u fix it about 2 hours?
thank you

**Comment by hasanitman** [comment]
Is there any hope to resolve it for 1 hours?
i very need it

**Comment by Jamie4224** [comment]
@JRoy Any progress on this?

**Comment by JRoy** [comment]
@Jamie4224 Yep! As no "official" way of fixing this issue has been released, I'm probably going to cut the stream at 50-58 minutes via the script instead of letting the stream hit the one-hour Instagram limit. I'd add a flag to bypass this but otherwise, I don't know what to do until an official method is released.

### **Escalated to 0.7 Release**

**Comment by Jamie4224** [comment]
I have a different idea that might help. It goes like this:

- Stream till 58 minute mark, give warning every minute from 55 minutes.
- Quit the stream at 58 minutes
- Generate a new stream so you can easily go on with a new stream key after 1 minute of copy/paste and hitting start again

Good idea?
