### ISSUE TITLE
trouble loggin in

### ISSUE THREAD

**Issue by foreverme234** [JRoy/InstagramLive-PHP#36]
hey, hoping someone can help.....

I was streaming to my instagram for about 20 mins, after stopping for 30 mins I got the below when trying to start again..

Loading InstagramLive-PHP v0.6...
PHP Warning:  require(C:\Users\blackrack3\Desktop\InstagramLive-PHP-0.6-RC-1\Ins
tagramLive-PHP-0.6-RC-1/vendor/autoload.php): failed to open stream: No such fil
e or directory in C:\Users\blackrack3\Desktop\InstagramLive-PHP-0.6-RC-1\Instagr
amLive-PHP-0.6-RC-1\goLive.php on line 21
PHP Fatal error:  require(): Failed opening required 'C:\Users\blackrack3\Deskto
p\InstagramLive-PHP-0.6-RC-1\InstagramLive-PHP-0.6-RC-1/vendor/autoload.php' (in
clude_path='.;C:\php\pear') in C:\Users\blackrack3\Desktop\InstagramLive-PHP-0.6
-RC-1\InstagramLive-PHP-0.6-RC-1\goLive.php on line 21

**Comment by JRoy** [comment]
Hey, try reinstalling the script, you appear to still be on RC-1

**Comment by CrypticKingJoe** [comment]
First I got 

C:\Users\User\Desktop\InstagramLive-PHP-master>php goLive.php
Loading InstagramLive-PHP v0.6...
PHP Warning:  require(C:\Users\User\Desktop\InstagramLive-PHP-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\User\Desktop\InstagramLive-PHP-master\goLive.php on line 21

Warning: require(C:\Users\User\Desktop\InstagramLive-PHP-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\User\Desktop\InstagramLive-PHP-master\goLive.php on line 21
PHP Fatal error:  require(): Failed opening required 'C:\Users\User\Desktop\InstagramLive-PHP-master/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Users\User\Desktop\InstagramLive-PHP-master\goLive.php on line 21

Fatal error: require(): Failed opening required 'C:\Users\User\Desktop\InstagramLive-PHP-master/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Users\User\Desktop\InstagramLive-PHP-master\goLive.php on line 21
Then I go to releases > v0.6 Release Candidate 1 and then

C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1>php goLive.php
Loading InstagramLive-PHP v0.6...
PHP Warning:  require(C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1\goLive.php on line 21

Warning: require(C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1/vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1\goLive.php on line 21
PHP Fatal error:  require(): Failed opening required 'C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1\goLive.php on line 21

Fatal error: require(): Failed opening required 'C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\Users\User\Desktop\InstagramLive-PHP-0.6-RC-1\goLive.php on line 21

**Comment by JRoy** [comment]
You didn't follow the setup instructions
