### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Mattkillsyou** [JRoy/InstagramLive-PHP#37]
Getting this weird error below

  Problem 1
    - Installation request for mgp25/instagram-php dev-master -> satisfiable by mgp25/instagram-php[dev-master].
    - mgp25/instagram-php dev-master requires ext-curl * -> the requested PHP extension curl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\Users\User\Documents\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by JRoy** [comment]
[View a tutorial here](http://www.tomjepson.co.uk/enabling-curl-in-php-php-ini-wamp-xamp-ubuntu/) use option one and skip step 6
