### ISSUE TITLE
Implement Async Comment Processing

### ISSUE THREAD

**Issue by JRoy** [JRoy/InstagramLive-PHP#4]
Use some sync method to call comments and system comments so they can be archived.

**Comment by AnitaPazhohesh** [comment]
We will try it to see how it works!
Thanks!
Anita

**Comment by mahdisalimi66** [comment]
Can you install and test the spatie/async package ?

**Comment by mahdisalimi66** [comment]
Thank you very much  ,I can not  run Live for more than an hour please help me

**Comment by JRoy** [comment]
@mahdisalimi66, I've done some testing and it turns our only verified users can live stream for more than an hour

**Comment by mahdisalimi66** [comment]
That is Only verified user in instagram can live stream for more than an hour ?

**Comment by JRoy** [comment]
@mahdisalimi66: Correct

**Comment by JRoy** [comment]
Ya no problem and I'm sorry abt it, out of my control

**Comment by mahdisalimi66** [comment]
Confirmation of the account is very difficult. I can not do it

**Comment by JRoy** [comment]
Exactly, I cannot help with this as it's out of my control

**Comment by JasonRWallace7** [comment]
Hello - I keep getting this error Account Flagged: Please sign out of all phones and try logging into instagram.com from this computer before trying to run this script again!
even though I have logged out of all devices. any suggestions ?

**Comment by dannie9099** [comment]
Please I have been getting this error 

Loading InstagramLive-PHP v0.4...
Logging into Instagram...
Account Flagged: Please sign out of all phones and try logging into instagram.com from this computer before trying to run this script again!

I have signed out of phones. and signed in using my computer yet error persists...

Kindly help out...

Thank you

**Comment by JRoy** [comment]
@JasonRWallace7 and @dannie9099 please do not ask for help in existing issues, please create a new issue and I will help you

**Comment by AnitaPazhohesh** [comment]
Hello again JRoy,
I’ve just read your response to another user about  applying spatie/async to bypass the one hour time limit on Instagram Live! So just to make sure I understand this correctly, this script can not be used on Windows along with your live.php OR the Instagram does not allow no verified accounts to go live beyond the one hour limit? Which one? Is there any other solution?
Please verify the above and also let me know how if at all I can use 2 instances of your php script on the same PC to go live at the same time on 2 different Instagram account? As an example I sometimes run Live from the same PC on 2 Facebook accounts simultaneously using 2 instances of Wirecast streaming software.
Thanks much.
Anita

**Comment by JRoy** [comment]
You cannot go more than an hour live if you do not have a verified account. And as far as I know yes you can stream multiple accounts at the same time

**Comment by AnitaPazhohesh** [comment]
Great! Thanks again for your prompt response.

**Comment by JRoy** [comment]
This issue will be resolved with InstagramLive-PHP v0.5

So far I can only promise async comment & like viewing on **Windows [7+]** as I am using Windows's [`start`](https://ss64.com/nt/start.html) command to run an additional script/window that will interpret commands and send them back to the main script/window for the commands to actually be ran. The main script will run the commands from the second window. The main window/script will display comments/likes and log messages **only**.

I will look into at least Linux support for a future version of the script but for now at least Windows support is my main priority.

**P.S.** The script will still "support" Linux and Mac but you will not be able to see live comments/likes. Basically the script will act as it currently does in v0.4. I am not sure if I will be backporting any new commands to legacy Linux support but the streaming backend handler will be maintained.

If you have any questions, please ask them in our discord: [https://discord.gg/2nz436f](https://discord.gg/2nz436f)

Thanks,
Josh

**Comment by JRoy** [comment]
Added in v0.5-BETA-1
