### ISSUE TITLE
Any suggestions for streaming in landscape?

### ISSUE THREAD

**Issue by PomegranateApps** [JRoy/InstagramLive-PHP#46]
This works great but are there any suggestions to stream in landscape?

**Comment by JRoy** [comment]
I don't understand what you mean by landscape as Instagram only accepts vertical video.

**Comment by PomegranateApps** [comment]
Yes, I know. I just wondering if anyone has figured out any clever way to show landscape video or otherwise present it in a way that looks better.

**Comment by JRoy** [comment]
Rotate the content and make the viewer turn thier screen?

**Comment by habibinaj** [comment]
> 
> 
> Rotate the content and make the viewer turn their screen?

is there any way other than rotating the output in the software? because that way your not able to stream on 2 different  output at the same time cause one needs landscape output like Facebook and one needs vertical output like Instagram. is there any solution for this?

**Comment by njokusomto** [comment]
A fix for this would be very helpful. Maybe a flag with the goLive command that will rotate the incoming video feed.

Thanks for all the good work again @JRoy!

**Comment by JohnTrabusca** [comment]
You can edit obs script to take a template to rotate the source you're getting. I managed to do that and it's working flawless

**Comment by JRoy** [comment]
@njokusomto, this script doesn't modify or see the incoming video at all so unfortunately that's something you'd have to do in obs or whatever video encoder you're using.

**Comment by njokusomto** [comment]
Thanks for your timely feedback as always.
The challenge is I do not stream via OBS. We use a streaming kit that sends to Restream to stream to multiple platforms simultaneously. But, I absolutely understand your position @JRoy and @JohnTrabusca.

I'll hope that Instagram comes around pretty soon on this.
Thanks again for all your support!
