### ISSUE TITLE
CURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by alicankablan** [JRoy/InstagramLive-PHP#47]
Everything is okey but if I am try to connect this errors is raising.

C:\xx\InstagramLive-PHP-master>php goLive.php
Loading InstagramLive-PHP v0.7.1...
Logging into Instagram, This can take up-to two minutes. Please wait...
Error While Logging in to Instagram: Network: CURL error 6: Could not resolve host: i\.instagram.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
===========BEGIN DUMP===========
InstagramLive-PHP Version: 0.7.1
Operating System: WINNT
PHP Version: 7.2.12
PHP Runtime: cli
true
Composer Lock: true
Vendor Folder: true
============END DUMP============

**Comment by JRoy** [comment]
This is an issue with your DNS settings. Try switching to a more modern DNS server like 1.1.1.1
Goto https://1.1.1.1 for instructions on how to change your DNS server on your device.
