### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by jasspace1900** [JRoy/InstagramLive-PHP#48]
Hi I really need some help. I've been trying to broadcast a pre recorded video to Instagram live for a few months now. I have tried several things and have been scammed a few times :/ I was offered by one company to pay $60 month for me to use their service which actually works flawless but I cant afford to pay $60 every month but i didn't require me to do nothing but upload my video, stream, press stop and save so it was simple but, besides someone had offered to help me set it up with obs but they haven't got back with me in the last few days. so i found this and im not sure what to do. Im actually new to programming. So how does your creation work could you help me? Im am willing to pay a reasonable price for help at this point thanks so much :)

**Comment by JRoy** [comment]
Hello! I'd be willing to to help you for free (donations are always appreciated however :P). Add me on discord: Joshie#0001 so we can talk easier
