### ISSUE TITLE
error 60 on first run

### ISSUE THREAD

**Issue by sneaky4oe** [JRoy/InstagramLive-PHP#5]
I've never worked with PHP, running this on windows. Installecd PHP manually, enabled extensions, added to path, then tried to run, and got this error:

> Error While Logging in to Instagram: Network: CURL error 60: SSL certificate problem: unable to get
> local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

Any hints? I really have no idea what to do.

**Comment by JRoy** [comment]
What is your OS and its version?

**Comment by sneaky4oe** [comment]
Windows 8.1

**Comment by JRoy** [comment]
Are you using proxy?

**Comment by sneaky4oe** [comment]
No, but I'm on VPN, since most of the web is locked out in Russia.

**Comment by JRoy** [comment]
Oh, that may be why. This error means Instagram cannot communicate securely with its servers. This can be caused with a VPN/different countries that do not trust the same CA's.

**Comment by sneaky4oe** [comment]
Same happens with several other servers and even other VPN providers.
Tried it without VPN as well. Instagram isn't blocked in Russia, so it's odd it doesn't work.

**Comment by leolobato** [comment]
I had the same issue on a fresh Windows PHP install where curl was not setup correctly:

https://github.com/yabacon/paystack-php/wiki/cURL-error-60:-SSL-certificate-problem:-unable-to-get-local-issuer-certificate-(see-http:--curl.haxx.se-libcurl-c-libcurl-errors.html)

**Comment by sneaky4oe** [comment]
@JRoy Previous comment worked. Can you please add the step to your setup guide?
