### ISSUE TITLE
Image and sharing

### ISSUE THREAD

**Issue by willswed** [JRoy/InstagramLive-PHP#50]
I believe that the PHP can be improved if you are looking to stay a bit longer, for while, than 1 hours.
So we could have a routine to bring new URL every hour.
But the worst thing is that we do not control the "SHARE" to keep the video in the "history" for 24 hours.
After the session ends by itself, we could have the option to select the live to "share your video for the next 24 hours"
https://www.bustle.com/p/can-you-rewatch-live-instagram-videos-heres-what-you-need-to-know-65549

If you can save the video in a command live, would be nice.

About the resolution, there is some kind of bug in quality and dimensions. I have been transmitting with the correctly dimensions and something the image goes "crazy" when I start.
We have to see a way to make it possible to control the dimensions somehow.

I also think that we could save an "automatically list of comments" in every live.

so it's almost perfect. But the keep the video running more than one hour and changing from URL to URL and saving the video "share" automatically WILL BE A PLUS!

**Comment by JRoy** [comment]
Please make sure to update to the latest version of the script. You should then be able to do `php goLive.php -i -a` to automatically start a new stream
