### ISSUE TITLE
2 factor issue

### ISSUE THREAD

**Issue by Ramacraft123** [JRoy/InstagramLive-PHP#51]
hi! i'm having problems while logging in to instagram.

Error While Logging in to Instagram: InstagramAPI\Response\LoginResponse: Please check the security code and try again.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 0.7.1
Operating System: WINNT
PHP Version: 7.1.8
PHP Runtime: cli
true
Composer Lock: true
Vendor Folder: true
============END DUMP============
i'm using lastpass 2fa for login. thanks

**Comment by JRoy** [comment]
Instagram is rejecting your 2fa code. Make sure you are not using spaces when typing your code

**Comment by Ramacraft123** [comment]
I've tried that, doesn't work. that means i can't use authenticator app then? :(
