### ISSUE TITLE
quality of streaming 

### ISSUE THREAD

**Issue by amirgani** [JRoy/InstagramLive-PHP#52]
i stream with pc but in android device quality is low 
i see in another accounts thats work very well in every device 
i stream with streamlabs obs 
any advice ?
thanks for your work

**Comment by JRoy** [comment]
Try using my obs settings
```json
{
  "name": "Instagram Live",
  "common": true,
  "servers": [
    {
      "name": "Default",
      "url": "rtmp://live-upload.instagram.com:80/rtmp/"
    }
  ],
  "recommended": {
    "keyint": 2,
    "profile": "main",
    "max video bitrate": 4000,
    "max audio bitrate": 128
  }
}
```

**Comment by amirgani** [comment]
where can i add this code ??

**Comment by amirgani** [comment]
my video bit rate is set on 5000 
and audio is 128 
in software setting 
but still i'm dealing with quality problem :(

**Comment by amirgani** [comment]
you can check this page to see the how amazing their quality and their live 24 hours per day
@manotoofficial
@JRoy

**Comment by JRoy** [comment]
Set your video bitrate to 4000

**Comment by lmcosta** [comment]
@JRoy I could not find where this Json file is.

Or should this be done directly in the OBS streaming properties?

**Comment by JRoy** [comment]
@lmcosta change the settings from obs's menus, don't edit json files
