### ISSUE TITLE
Retain Previous Stream output.txt

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#58]
Dear Roy

When the output file is made, in the next stream, the previous output file is removed and then the new output file is constructed. Can it be done to keep the previous Stream output file be maintained?
The other is that the viewers list is not save at the output file, can you save the viewers list in the output file?

Thank you.

**Comment by JRoy** [comment]
I can address the issue with output files deleting themselves but as for logging viewers, I can't make any promises as if I need to make a new request to log them, I won't do it
