### ISSUE TITLE
ssl ERROR

### ISSUE THREAD

**Issue by nzrii** [JRoy/InstagramLive-PHP#6]
Hello
plz help me

Error While Logging in to Instagram: Network: CURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

**Comment by JRoy** [comment]
What is your OS, Country and are you using a VPN or Proxy?

**Comment by JRoy** [comment]
No Response - Closing
