### ISSUE TITLE
Automate Resolution and Canvas Size 

### ISSUE THREAD

**Issue by ahmadd110** [JRoy/InstagramLive-PHP#65]
Dear Roy
Can auto correct size and rotate(for horizontal or landscape instead vertical) video in obs setting (obs.php)?
Thanks

**Comment by JRoy** [comment]
Hm, good idea. I don't know if this setting is able to be modified but I will look into it

**Comment by JRoy** [comment]
Looks like this is possible, all that needs editing is the `basic.ini` file in the same directory. 

Note to self: 
* Save Backups
* Replace ini with:
 ```ini
[General]
Name=Untitled

[Video]
BaseCX=720
BaseCY=1280
OutputCX=720
OutputCY=1280

[Output]
Mode=Simple

[SimpleOutput]
VBitrate=4000
```
