### ISSUE TITLE
Error While Logging in to Instagram: InstagramAPI\Response\LoginResponse: Sorry, there was a problem with your request.

### ISSUE THREAD

**Issue by h1rule** [JRoy/InstagramLive-PHP#68]
This happens when i try to login with one of my accounts (passwords are correct, 2FA disabled):

Error While Logging in to Instagram: InstagramAPI\Response\LoginResponse: Sorry, there was a problem with your request.

using the latest version, did all the steps from 1 to 6.

**Comment by JRoy** [comment]
@h1rule, please run the script with the argument `php goLive.php -d` and share the response

**Comment by h1rule** [comment]
LUL, it was because the Script didnt had write permissions. Maybe you Write this down in your step by step Tutorial, to set chmod +x permissions :)

**Comment by h1rule** [comment]
Anyway theres always this send code by sms or email verification thing. This script is not for me :(

**Comment by JRoy** [comment]
Please do the `php goLive.php -d` and share the response

**Comment by JRoy** [comment]
No response within 7 days - Closing
