### ISSUE TITLE
Error While Logging In To Instagram: Invalid Parameters

### ISSUE THREAD

**Issue by ThatCubedPerson** [JRoy/InstagramLive-PHP#7]
Hello, I am trying to log in to Instagram using the API but I have an error while logging in! I am running this on Mac OS X 10.10 Yosemite, I am not sure if anybody could help me with this but I am having trouble so it's probably better to ask than to not know.

Here is the issue:
`Loading InstagramLive-PHP v0.3...`
`Logging into Instagram...`
`Error While Logging in to Instagram: Invalid Parameters`

**Comment by JRoy** [comment]
I have never had this issue, did you make sure to follow the instructions?

**Comment by ThatCubedPerson** [comment]
I entered my username and password in the config.php file. So I don't know what I am doing wrong.

**Comment by JRoy** [comment]
Did you modify goLive.php at all?

**Comment by ThatCubedPerson** [comment]
No.

**Comment by JRoy** [comment]
Are you using a proxy/vpn and what country are you in?

**Comment by JRoy** [comment]
No response from user, closing!
