### ISSUE TITLE
Is this within the Facebook/Instagram guidelines?

### ISSUE THREAD

**Issue by kzka90** [JRoy/InstagramLive-PHP#71]
Question about live streaming with this. Is this within the Facebook/Instagram guidelines?

**Comment by JRoy** [comment]
Not really; Their terms of service are not being violated and there is little risk. However technically you're not allowed to run outside of the main client so that's that.

**Comment by kzka90** [comment]
Should we be using this on brand accounts with >500k followers? Or would it be too risky?

**Comment by JRoy** [comment]
As long as you don't play copyrighted music, you should be alright.
