### ISSUE TITLE
Search the Key

### ISSUE THREAD

**Issue by primo1983** [JRoy/InstagramLive-PHP#79]
Search the Key automatically, copying it to clipboard, without having to copy every moment that is transmitting to the OBS.
It's possible?

**Comment by JRoy** [comment]
I don't understand your question, can you clarify M

**Comment by primo1983** [comment]
when we generated the KEY on the command line, this KEY should already be imported directly into the OBS field:
Settings => Stream

**Comment by JRoy** [comment]
@primo1983 do you have windows?

**Comment by primo1983** [comment]
@JRoy Yep

**Comment by JRoy** [comment]
@primo1983 are you using OBS integration?

**Comment by primo1983** [comment]
Integrated? I do games broadcast.
Then I open the OBS and put the key generated by Instagram-Live

**Comment by primo1983** [comment]
I did what you said, but there you are giving the following error, see in the pictures.
Error
https://prnt.sc/mf8b60
.
Config CMD
https://prnt.sc/mf8bcl

**Comment by JRoy** [comment]
Switch to the default profile in obs

**Comment by primo1983** [comment]
see you do not have it
https://prnt.sc/mf90g1

**Comment by JRoy** [comment]
@primo1983 click rename and rename it to "Untitled"
