### ISSUE TITLE
Stream Key Character Count Too Long 

### ISSUE THREAD

**Issue by marcosgonzaleztv** [JRoy/InstagramLive-PHP#8]
Hi JRoy,

Thank you for this amazing work. I tried to use restream.io to broadcast my stream not only to twitch/youtube, but to Instagram as well. The issue I ran into (after talking to a restream dev) is that the stream key is too long for restream.io. They have a set character cap. 

Is there a way to decrease the character count, or is that on Instagrams side? 

Thanks!

**Comment by JRoy** [comment]
@dato309 is correct: Instagram controls the stream key length not me so nothing I can do sorry. Your best bet would be to ask restream to increase their length
