### ISSUE TITLE
OBS Studio - Auto Generate service.json

### ISSUE THREAD

**Issue by vmesquita** [JRoy/InstagramLive-PHP#82]
Would it be possible to generate the OBS Studio service.json file automatically?
This file is the configuration of the server url and key.
I think of using the --multi --portable parameter in OBS. In this way, this OBS will transmit exclusively to Instagram. The service.json file will be located in C: \ Program Files (x86) \ obs-studio \ basic \ profiles \ INSTAGRAM. In this case you would have an option to customize the location. After doing this, have option to start OBS automatically but with option to start OBS Studio with the parameters that I would need (--multi --portable, etc) ...
By stopping the live stream on the php command prompt, we also stop this same live stream from this OBS that was used.

**Comment by JRoy** [comment]
I already have obs integration, when you start the stream, it will prompt you to enable it. In the next update I'll be adding multi profile support. If this is not your issue please explain further

**Comment by JRoy** [comment]
@vmesquita in portable mode the working directory is unpredictable and therefore no way of automating it. Sorry
