### ISSUE TITLE
OBS Studio locking

### ISSUE THREAD

**Issue by zsvendo** [JRoy/InstagramLive-PHP#83]
When I execute OBS automatically through your file I realize that it is locking the streaming, if manual execution seems to go well.
Have you noticed that?
Windows platform
php goLive.php --obs --dcomments

**Comment by JRoy** [comment]
@zsvendo What do you mean by locking?

**Comment by zsvendo** [comment]
the image is locked,

**Comment by JRoy** [comment]
@zsvendo You can run the script with `--obs-no-stream` to stop auto streaming but keep automatic stream key/url input and resolution changing.

**Comment by zsvendo** [comment]
ok
