### ISSUE TITLE
STOP COMMAND

### ISSUE THREAD

**Issue by zsvendo** [JRoy/InstagramLive-PHP#84]
in all transmissions when the command STOP will end.
he does not continue to broadcast, he does not end the session.

**Comment by JRoy** [comment]
@zsvendo I do not understand, what's not working? What's your php version?

**Comment by zsvendo** [comment]
PHP 7.3.1

**Comment by zsvendo** [comment]
There are moments that do not send nor comments, when the comment command is used.

**Comment by zsvendo** [comment]
How could you not understand?
Let's go again.
When I end live streaming with the command cmd => c:/live php.exe stop
The connection is not terminated.
To do the disconnection I have to enter live by the cell there he drops the connection of the php

**Comment by JRoy** [comment]
@zsvendo The command is just `stop`, not `c:/live php.exe stop` and you must be running inside the script to use `stop`

**Comment by zsvendo** [comment]
yes friend that all I know, I'll even simulate here for you I'm a 17 year old developer, I know a lot of php, and a lot of language.

**Comment by JRoy** [comment]
@zsvendo Okay, I'm sorry if I'm not understanding you here, I'm trying my best. When you run the `stop` command, do you get an error? Does the stream stop on Instagram?

**Comment by zsvendo** [comment]
I do not receive any errors, but it does not stop the connection with instagram, the instance stays open, by what I observe.

Sometimes it works, but sometimes it does not.

**Comment by zsvendo** [comment]
Do you have any logs to track this?

**Comment by JRoy** [comment]
Then I have no idea what to do, this is most likely an Instagram issue and not an issue with the script
