### ISSUE TITLE
Overhaul command system and port older commands to legacy

### ISSUE THREAD

**Issue by lud4l** [JRoy/InstagramLive-PHP#91]
Hello,

Do you plan to make the 1.2 features (like auto-pin) available on MacOS ?

Thanks a lot for your work by the way, where could I donate? :)

**Comment by JRoy** [comment]
I've been looking it to overhauling and command system and porting features to macos/linux. Will add in next version

**Comment by JRoy** [comment]
You can also donate here: https://github.com/JRoy/InstagramLive-PHP/blob/master/README.md#donate

:)

**Comment by lud4l** [comment]
Ok great, thanks!

**Comment by JRoy** [comment]
@lud4l: Backported a few commands as well as auto-pin command line option in 1.3

Changelog: https://github.com/JRoy/InstagramLive-PHP/releases/tag/1.3

Cheers!
