### ISSUE TITLE
Auto-pin don't keep it when watching a live

### ISSUE THREAD

**Issue by lud4l** [JRoy/InstagramLive-PHP#95]
Hello,

thanks for the 1.3 and the backporting, i'll try it on Mac on monday.

I have an issue about auto-pin : when activate, the auto-pin works (and is viewable when you access the live).
But after a few seconds, it doesn't stay pined and become a standard comment (so it disappear as it get it back to its position)

Is it a normal behavior?

**Comment by JRoy** [comment]
This is not normal behavior and I can't reproduce this and must be an Instagram issue, I'd wait a bit and see if it still happens

**Comment by lud4l** [comment]
Ok thanks, tell me if you need a screencapture of this bug

**Comment by lud4l** [comment]
Just did some test with several devices, it's a "local" bug on my own phone (iphone 8 iOS 12), watching the live.
So nothing to do here i guess.
Thanks for your help by the way!

**Comment by lud4l** [comment]
and your backporting is working fine on MacOS 10.12.6 (sierra). thanks again!
