### ISSUE TITLE
In-live "comment" bug

### ISSUE THREAD

**Issue by lud4l** [JRoy/InstagramLive-PHP#97]
I tried to send a comment using the in-live `comment` command, here is the output :

> comment this_is_a_test_#comment
> Invalid command. Type "help" for help!

Did i something wrong?

**Comment by zsvendo** [comment]
@lud4l  Yes, you must write comment, enter soon then write comment
1- comment
2 - enter
3 - Hello World!

**Comment by JRoy** [comment]
^

**Comment by lud4l** [comment]
Ok thanks, sorry for being such a noob ;)

**Comment by lud4l** [comment]
should I put "_" for space or should i wrote it normally?

**Comment by JRoy** [comment]
Yes
